/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutorial5;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author 20181041110014
 */
public class NotePad extends javax.swing.JFrame {

    /**
     * Creates new form NotePad
     */
    public NotePad() {
        initComponents();
    }

    public JTextArea getAreadetexto() {
        return areadetexto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areadetexto = new javax.swing.JTextArea();
        menu = new javax.swing.JMenuBar();
        item2 = new javax.swing.JMenu();
        localizar = new javax.swing.JMenuItem();
        substituir = new javax.swing.JMenuItem();
        item3 = new javax.swing.JMenu();
        fonte = new javax.swing.JMenuItem();
        item4 = new javax.swing.JMenu();
        barradeferramentas = new javax.swing.JMenuItem();
        barradestatus = new javax.swing.JMenuItem();
        item5 = new javax.swing.JMenu();
        exibirajuda = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenuItem();
        item1 = new javax.swing.JMenu();
        novo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        salvar = new javax.swing.JMenuItem();
        fechar = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areadetexto.setColumns(20);
        areadetexto.setRows(5);
        jScrollPane1.setViewportView(areadetexto);

        item2.setText("Editar");

        localizar.setText("Localizar");
        item2.add(localizar);

        substituir.setText("Substituir");
        item2.add(substituir);

        menu.add(item2);

        item3.setText("Formatar");

        fonte.setText("Fonte");
        fonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fonteActionPerformed(evt);
            }
        });
        item3.add(fonte);

        menu.add(item3);

        item4.setText("Exibir");

        barradeferramentas.setText("Barra de Ferramentas");
        item4.add(barradeferramentas);

        barradestatus.setText("Barra de Status");
        item4.add(barradestatus);

        menu.add(item4);

        item5.setText("Ajuda");

        exibirajuda.setText("Exibir Ajuda");
        item5.add(exibirajuda);

        sobre.setText("Sobre o Bloco de Notas");
        item5.add(sobre);

        menu.add(item5);

        item1.setText("Arquivo");
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });

        novo.setText("Novo Arquivo");
        item1.add(novo);

        abrir.setText("Abrir Arquivo");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        item1.add(abrir);

        salvar.setText("Salvar Arquivo");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        item1.add(salvar);

        fechar.setText("Fechar Arquivo");
        item1.add(fechar);

        sair.setText("Sair");
        item1.add(sair);

        menu.add(item1);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        JFileChooser salva = new JFileChooser();
        int opcao = salva.showSaveDialog(this);
        try {
            FileWriter arquivo = new FileWriter(salva.getSelectedFile().getPath());
            BufferedWriter saida = new BufferedWriter(arquivo);
            saida.write(areadetexto.getText());
            saida.close();
        } catch (IOException ex) {
            Logger.getLogger(NotePad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        JFileChooser abre = new JFileChooser();
        int opcao = abre.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION){
            areadetexto.setText("");
            try {
                Scanner scan = new Scanner(new FileReader(abre.getSelectedFile().getPath()));
                while (scan.hasNext()){
                    areadetexto.append(scan.nextLine() + "\n");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NotePad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ActionPerformed

    private void fonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fonteActionPerformed
        FormatarFonte fonte = new FormatarFonte (this, false);
        fonte.setVisible(true);
    }//GEN-LAST:event_fonteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotePad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JTextArea areadetexto;
    private javax.swing.JMenuItem barradeferramentas;
    private javax.swing.JMenuItem barradestatus;
    private javax.swing.JMenuItem exibirajuda;
    private javax.swing.JMenuItem fechar;
    private javax.swing.JMenuItem fonte;
    private javax.swing.JMenu item1;
    private javax.swing.JMenu item2;
    private javax.swing.JMenu item3;
    private javax.swing.JMenu item4;
    private javax.swing.JMenu item5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem localizar;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem novo;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem salvar;
    private javax.swing.JMenuItem sobre;
    private javax.swing.JMenuItem substituir;
    // End of variables declaration//GEN-END:variables
}
